default:
	@javac *.java
	@echo successfully compiled.

clean:
	@rm -f *.class
	@echo successfully cleaned.

run_test1:
	@java Simulator TestOne/config.cfg 50 2

run_test2:
	@java Simulator TestTwo/config.cfg 50 2

run_test3:
	@java Simulator TestThree/config.cfg 50 2

run_test4:
	@java Simulator TestFour/config.cfg 50 2

